repos:
  -   repo: local
      hooks:
      - id: isort
        name: (Isort) Import Sorting and Organization
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: (Black) Code Formatting and Style Enforcement
        entry: poetry run black --line-length 120 src
        language: system
        types: [python]
      - id: pylint
        name: (Pylint) Code Linting and Style Check.
        entry: poetry run pylint --rcfile=.pylintrc
        language: system
        types: [python]
